import { useParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, ExternalLink, CheckCircle, Share2, Copy } from 'lucide-react';
import { getInvoice } from '../../services/api';
import { useState } from 'react';

export default function ReceiptPage() {
  const { invoiceId } = useParams<{ invoiceId: string }>();
  const navigate = useNavigate();
  const [copiedField, setCopiedField] = useState<'invoice' | 'tx' | null>(null);

  const { data: invoiceRes, isLoading } = useQuery({
    queryKey: ['invoice', invoiceId],
    queryFn: () => getInvoice(invoiceId!),
    enabled: !!invoiceId,
  });

  const invoice = invoiceRes?.data;

  const copyToClipboard = (text: string, field: 'invoice' | 'tx') => {
    navigator.clipboard.writeText(text).then(() => {
      setCopiedField(field);
      setTimeout(() => {
        setCopiedField(null);
      }, 1500);
    });
  };

  const handleShare = async () => {
    if (!invoice || !navigator.share) return;
    try {
      await navigator.share({
        title: 'ZeroPay Receipt',
        text: [
          `Payment of ₹${(invoice.amountPaise / 100).toFixed(2)} (${(invoice.amountLovelace / 1_000_000).toFixed(4)} ADA) settled on Cardano.`,
          `Invoice: ${invoice.invoiceId}`,
          invoice.txHash ? `TX: ${invoice.txHash}` : '',
          invoice.receiptCid ? `IPFS: https://gateway.pinata.cloud/ipfs/${invoice.receiptCid}` : '',
        ].filter(Boolean).join('\n'),
        url: window.location.href,
      });
    } catch (err) {
      // User cancelled or error — silently ignore
    }
  };

  const getTimelineSteps = () => {
    const status = invoice?.status || 'pending';
    const isSubmitted = !!invoice?.txHash || ['submitted', 'confirming', 'confirmed', 'settled'].includes(status);
    const isConfirmed = ['confirmed', 'settled'].includes(status);
    const isSettled = status === 'settled';

    return [
      {
        label: 'Invoice Created',
        description: 'Invoice generated by merchant',
        time: invoice?.createdAt ? new Date(invoice.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : null,
        done: true,
      },
      {
        label: 'Payment Submitted',
        description: invoice?.txHash 
          ? `TX: ${invoice.txHash.slice(0, 8)}...${invoice.txHash.slice(-6)}` 
          : 'Awaiting payment broadcast',
        time: invoice?.submittedAt ? new Date(invoice.submittedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : null,
        done: isSubmitted,
      },
      {
        label: 'Cardano Confirmed',
        description: isConfirmed 
          ? `Verified on-chain (3+ confs)` 
          : 'Waiting for blockchain verification',
        time: invoice?.confirmedAt ? new Date(invoice.confirmedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : null,
        done: isConfirmed,
      },
      {
        label: 'Receipt Settled',
        description: isSettled 
          ? `Receipt pinned to IPFS CID: ${invoice?.receiptCid?.slice(0, 8)}...` 
          : 'Generating IPFS receipt',
        time: invoice?.settledAt && isSettled ? new Date(invoice.settledAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : null,
        done: isSettled,
      },
    ];
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-surface flex items-center justify-center">
        <div className="w-6 h-6 border-2 border-teal-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-surface px-5 pt-12 pb-10">
      <button onClick={() => navigate(-1)} className="btn-ghost flex items-center gap-2 -ml-2 mb-8">
        <ArrowLeft size={18} /> Back
      </button>

      {invoice ? (
        <div className="max-w-md mx-auto animate-fade-in">
          <div className="relative mb-8">
            <div className="absolute inset-0 bg-status-confirmed blur-3xl opacity-10 rounded-full scale-150 animate-pulse" />
            <div className="relative text-center">
              <div className="w-20 h-20 rounded-full bg-status-confirmed/10 flex items-center justify-center mx-auto mb-4 border-4 border-surface shadow-lg">
                <CheckCircle size={40} className="text-status-confirmed animate-bounce" />
              </div>
              <h1 className="text-3xl font-bold">Payment Settled</h1>
              <p className="text-text-secondary mt-1">Your transaction has been processed</p>
            </div>
          </div>

          <div className="card space-y-6 mb-6 p-6">
            <div className="text-center pb-6 border-b border-surface-border">
              <p className="text-sm text-text-secondary mb-1">Total Paid</p>
              <p className="text-5xl font-bold text-teal-400">₹{(invoice.amountPaise / 100).toFixed(2)}</p>
              <p className="font-mono text-text-muted mt-2">
                {(invoice.amountLovelace / 1_000_000).toFixed(4)} ADA
              </p>
            </div>

            <div className="space-y-4">
              <div className="flex justify-between items-center text-sm">
                <span className="text-text-secondary">Invoice ID</span>
                <button
                  onClick={() => copyToClipboard(invoice.invoiceId, 'invoice')}
                  className="font-mono text-text-primary text-xs hover:text-teal-400 flex items-center gap-1.5 transition-colors relative py-1 px-2 rounded hover:bg-surface-elevated"
                >
                  {invoice.invoiceId}
                  <Copy size={12} className="opacity-60" />
                  {copiedField === 'invoice' && (
                    <span className="absolute -top-7 right-0 bg-zinc-800 text-white text-[10px] px-2 py-0.5 rounded shadow animate-fade-in whitespace-nowrap z-10">
                      Copied!
                    </span>
                  )}
                </button>
              </div>

              <div className="flex justify-between items-center text-sm">
                <span className="text-text-secondary">Network</span>
                <span className="text-text-primary font-medium">Cardano (Preprod)</span>
              </div>

              <div className="flex justify-between items-center text-sm">
                <span className="text-text-secondary">Rate</span>
                <span className="text-text-primary font-mono">₹{invoice.adaInrRate?.toFixed(2)}/ADA</span>
              </div>

              <div className="flex justify-between items-center text-sm">
                <span className="text-text-secondary">Timestamp</span>
                <span className="text-text-primary font-medium">{new Date(invoice.createdAt).toLocaleString()}</span>
              </div>

              {invoice.txHash && (
                <div className="flex justify-between items-center text-sm pt-3 border-t border-surface-border">
                  <span className="text-text-secondary">Tx Hash</span>
                  <button
                    onClick={() => copyToClipboard(invoice.txHash!, 'tx')}
                    className="font-mono text-text-primary text-xs hover:text-teal-400 flex items-center gap-1.5 transition-colors relative py-1 px-2 rounded hover:bg-surface-elevated max-w-[60%] truncate"
                  >
                    {invoice.txHash.slice(0, 6)}...{invoice.txHash.slice(-6)}
                    <Copy size={12} className="opacity-60" />
                    {copiedField === 'tx' && (
                      <span className="absolute -top-7 right-0 bg-zinc-800 text-white text-[10px] px-2 py-0.5 rounded shadow animate-fade-in whitespace-nowrap z-10">
                        Copied!
                      </span>
                    )}
                  </button>
                </div>
              )}

              {invoice.receiptCid && (
                <div className="flex justify-between items-center text-sm pt-3 border-t border-surface-border">
                  <span className="text-text-secondary">IPFS Receipt</span>
                  <a
                    href={`https://gateway.pinata.cloud/ipfs/${invoice.receiptCid}`}
                    target="_blank"
                    rel="noreferrer"
                    className="text-xs text-teal-400 hover:text-teal-300 flex items-center gap-1 transition-colors max-w-[60%] truncate font-mono"
                  >
                    {invoice.receiptCid.slice(0, 6)}...{invoice.receiptCid.slice(-6)}
                    <ExternalLink size={12} className="shrink-0" />
                  </a>
                </div>
              )}
            </div>

            {invoice.txHash && (
              <div className="pt-4 border-t border-surface-border space-y-3">
                <a
                  href={`https://preprod.cardanoscan.io/transaction/${invoice.txHash}`}
                  target="_blank"
                  rel="noreferrer"
                  className="w-full btn-secondary flex items-center justify-center gap-2 text-sm"
                >
                  <ExternalLink size={14} />
                  View on Explorer
                </a>
              </div>
            )}
          </div>

          {/* Vertical Transaction Timeline */}
          <div className="card p-6 mb-6">
            <h3 className="font-bold text-sm text-text-primary mb-5">Transaction Timeline</h3>
            <div className="relative border-l-2 border-surface-border pl-6 space-y-6 ml-2">
              {getTimelineSteps().map((step, idx) => (
                <div key={idx} className="relative">
                  {/* Circle Indicator */}
                  <div className={`absolute -left-[34px] top-0.5 w-4 h-4 rounded-full flex items-center justify-center border ${
                    step.done 
                      ? 'bg-teal-600 border-teal-600 text-white shadow-[0_0_10px_rgba(20,169,154,0.3)]' 
                      : 'bg-surface border-surface-border text-text-muted'
                  }`}>
                    {step.done ? (
                      <svg className="w-2.5 h-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                    ) : (
                      <div className="w-1.5 h-1.5 rounded-full bg-text-muted/40 animate-pulse" />
                    )}
                  </div>
                  {/* Content */}
                  <div className="flex justify-between items-start gap-4">
                    <div>
                      <p className={`text-sm font-semibold leading-none ${step.done ? 'text-text-primary' : 'text-text-muted'}`}>
                        {step.label}
                      </p>
                      <p className="text-xs text-text-secondary mt-1.5 leading-relaxed">{step.description}</p>
                    </div>
                    {step.time && (
                      <span className="text-[10px] text-text-muted font-mono font-medium bg-surface-elevated px-2 py-0.5 rounded-md">
                        {step.time}
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {'share' in navigator && (
            <button
              id="share-receipt-btn"
              onClick={handleShare}
              className="btn-secondary w-full flex items-center justify-center gap-2 mb-8"
            >
              <Share2 size={16} /> Share Receipt
            </button>
          )}
        </div>
      ) : (
        <div className="text-center py-20">
          <p className="text-text-muted">Receipt not found.</p>
        </div>
      )}
    </div>
  );
}
